Add record step

diff --git a/odb-experience/Dockerfile b/odb-experience/Dockerfile
--- a/odb-experience/Dockerfile
+++ b/odb-experience/Dockerfile
@@ -1,5 +1,4 @@
-FROM cypress/base:10
+FROM cypress/included:3.2.0
 
-npm install --ignore-scripts
-
-npx cypress run --record --parallel --key fe2fd7df-6282-48eb-8992-dee46aad089d --group odbx-e2e --ci-build-id $CODEBUILD_INITIATOR-$(cat $CODEBUILD_SRC_DIR_buildNumber_Artifact/buildNumber.txt) || echo "Tests failed but will continue deploy"
+RUN npm install --ignore-scripts
+RUN npx cypress run --record --parallel --key fe2fd7df-6282-48eb-8992-dee46aad089d --group odbx-e2e --ci-build-id $CODEBUILD_INITIATOR-$(cat $CODEBUILD_SRC_DIR_buildNumber_Artifact/buildNumber.txt) || echo "Tests failed but will continue deploy"
